name: Frizz ci

on: [ push ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable]
    steps:
      - name: Install Wix
        if: matrix.build == 'windows-latest'
        uses: actions/checkout@v2
        with:
          repository: fbarresi/wix
          path: wix
      - name: Install dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install alien build-essential fakeroot devscripts
      - uses: actions/checkout@v1
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Generate release tag and build
        id: tag
        shell: bash
        run: |
          VERSION=`grep version Cargo.toml | head -n1| awk '{ print $3 }'|tr -d '"'`-${{github.run_number}}
          echo "::set-output name=release_tag::$VERSION"
          ./test-suite/run-tests.sh

      - name: build deb,rpm
        if: matrix.os == 'ubuntu-latest'
        run: |
          set -x
          cargo build --release
          cargo install --force cargo-deb
          cargo deb --deb-version ${{ steps.tag.outputs.release_tag }}
          DEBFILE=`find -name *.deb`
          sudo alien --nopatch -r $DEBFILE

      - name: build msi
        if: matrix.os == 'windows-latest'
        run: |
          cargo build --release
          cargo install cargo-wix
          cargo wix --version
          cargo wix init
          cargo wix --output ./target/wix/frizz.msi

      - name: build msi
        if: matrix.os == 'macos-latest'
        run: |
          set -x
          cargo build --release
          cargo build --target x86_64-apple-darwin

      - name: Release with Notes
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.deb
            *.rpm
            *.msi
          tag_name: ${{ steps.tag.outputs.release_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

